---
version: "3.7"

services:
  test:
    image: quay.io/mojanalytics/concourse-worker-cleaner:${BUILD_TAG:-latest}
  inspec:
    image: chef/inspec:current
    environment:
      - CHEF_LICENSE=accept-no-persist
    entrypoint: sh  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tests:/share/tests
