---
version: "3.7"

services:
  test:
    image: 593291632749.dkr.ecr.eu-west-1.amazonaws.com/concourse-worker-cleaner:${BUILD_TAG:-local}
    entrypoint: ["/bin/sh", "-c", "sleep 600"]
  inspec:
    image: chef/inspec:current
    environment:
      - CHEF_LICENSE=accept-no-persist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tests:/share/tests
