---
name: Concourse Workers Cleaner Build & Test

"on":
  pull_request:
  push: { branches: [main] }

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Install Inspec
        uses: actionshub/chef-install@1.1.0
        with: { project: inspec }
      - name: Test
        run: make test
